# docker compose up --build --remove-orphans
# docker compose up --watch --build --remove-orphans
version: '3'
name: ado-asana-sync

services:
  sync:
    image: ghcr.io/danstis/ado-asana-sync:latest
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .devcontainer
            - .github
            - .vscode
            - data
            - tests
    volumes:
      - ./data:/app/data
    environment:
      ADO_PAT: ${ADO_PAT}
      ADO_URL: ${ADO_URL}
      ASANA_TOKEN: ${ASANA_TOKEN}
      ASANA_WORKSPACE_NAME: ${ASANA_WORKSPACE_NAME}
