name: Run pr agent on pull requests, respond to user comments

on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@e6ef3c0adfbe1c5ffc6818f8dd420c74c8dc6ea8 # main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
